### ISSUE TITLE
Event not thrown for VWA simple facet type assignment

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#27]
When assigning a type to the simple facet of a VWA the type is set but the event is not published. Debugger showed that the owning entity on the TLSimpleFacet was null and that publishEvent() could not find the owning model so it skipped publishing.  I did not check to see if Core Simple Facet has the same problem.

Workaround added to Type.setAssignedType() but does not assure sync of type assignments with TLModel. (not committed yet).

From TestTypes.java:
	// Simple facet of a VWA
		VWA_Node vwa = ml.addVWA_ToLibrary(ln, "Vwa1");
		vwa.setAssignedType(type1);

**Comment by slivezey** [comment]
The simple facet for a VWA is a GUI construct that does not exist in the compiler's TLValueWithAttributes class.  Since it is functionally separate from the compiler model, the event cannot be published by normal means unless something is added to the GUI code to propagate the event.

Since this is a GUI-specific problem, I am closing this bug against the compiler.
