### ISSUE TITLE
New Simple type in patch throws validation error

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#28]
Create a patch library and add a simple type then validate. A validation error (illegal patch) is reported. 

Page 36 of the reference specification says that simple types are allowed.

See org.opentravel.schemas.controllers.repository.VersionsTest.testPatch() for test case.

**Comment by slivezey** [comment]
During the recent refactoring of the compiler's versioning subsystem, the validation rules were changed as to which OTM entity types are allowed in patch version libraries.  At this time, the only entity allowed in patch versions is the TLExtensionPointFacet.

Closing this issue since the current functionality works-as-designed.
