### ISSUE TITLE
Listener callbacks for extensions

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#29]
GUI is not using these callbacks yet so this is minor for now.  But in testing (junit NewComponent_Tests) i found that VWA and closed enumerations were not calling the listener back. I checked the VWA and it has a listener and parent type assigned. The closed enum also had listener and extension values.

07:37:55,242 | DEBUG | NewComponent_Tests               | Extension owner: testInitialBO
07:37:55,339 | DEBUG | BaseNodeListener                 | Ownership event: EXTENDS_ADDED this = testInitialBO affected = null
07:37:55,359 | DEBUG | NewComponent_Tests               | Extension owner: UnmanagedBO
07:37:55,447 | DEBUG | BaseNodeListener                 | Ownership event: EXTENDS_ADDED this = UnmanagedBO affected = null
07:37:55,460 | DEBUG | NewComponent_Tests               | Extension owner: UnmanagedVWA
07:37:55,563 | DEBUG | NewComponent_Tests               | Extension owner: UnmanagedCE
07:37:55,671 | DEBUG | NewComponent_Tests               | Extension owner: UnmanagedCO
07:37:55,766 | DEBUG | BaseNodeListener                 | Ownership event: EXTENDS_ADDED this = UnmanagedCO affected = null
07:37:55,775 | DEBUG | NewComponent_Tests               | Extension owner: UnmanagedOE
07:37:55,855 | DEBUG | BaseNodeListener                 | Ownership event: EXTENDS_ADDED this = UnmanagedOE affected = null

**Comment by slivezey** [comment]
I was not able to reproduce this issue for the Closed Enumerations.  It is important to be sure that the entity has been added to the owning library before adding the TLExtension in order for the EXTENDS_ADDED event to be fired.

In the case of a VWA, an EXTENDS_ADDED event cannot be fired since VWA's do not formally use a TLExtension object to define their extension.  Instead, the listener should look for a Value Change Event of type TYPE_ASSIGNMENT_MODIFIED on the base VWA.
