### ISSUE TITLE
PropertyCodegenUtils and choice facets

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#31]
The list is always empty, even for the test case of the ExtendedChoice in library_1p2

List<TLAttribute> tlAttrs = PropertyCodegenUtils.getInheritedFacetAttributes((TLFacet) n.getTLModelObject());

**Comment by slivezey** [comment]
Unable to reproduce.  It is possible that this has been fixed since the original issue was reported back in December.  Also this functionality may not have been back-ported into the 3.2 release branch which was active at the time this issue was logged.

I am closing this issue for now, but we can re-open if the behavior can be reproduced on the 4.0 codebase.
